name: Docker CI

on:
  push:
    branches:
      - docker-setup
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t lab1_ptsd:latest .

    - name: Run tests in Docker container
      run: docker run --rm lab1_ptsd:latest

